// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tdmvaiufwxojvnojakvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbXZhaXVmd3hvanZub2pha3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2Nzg0NjcsImV4cCI6MjA4MDI1NDQ2N30.yORS13PGioOTxteeOIiMGj7UVGLCz7iTFjs41hsIRpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);